"""add cooked flag to recipes

Revision ID: 32316ea85c11
Revises: b470597e21b7
Create Date: 2026-08-08 12:25:02.615837
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '32316ea85c11'
down_revision: str | Sequence[str] | None = 'b470597e21b7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('cooked', sa.Boolean(), nullable=False,
                                       server_default=sa.false()))
    op.create_index(op.f('ix_recipes_cooked'), 'recipes', ['cooked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_cooked'), table_name='recipes')
    op.drop_column('recipes', 'cooked')
    # ### end Alembic commands ###
