"""inventory_items catalog

Revision ID: e158a335e2f2
Revises: e5f6a7b8c9d0
Create Date: 2026-08-25 05:38:02.202398
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e158a335e2f2'
down_revision: str | Sequence[str] | None = 'e5f6a7b8c9d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False, comment='Surrogate primary key.'),
    sa.Column('name', sa.String(length=120), nullable=False, comment='Food name; unique catalog key (case-insensitive dedup in the repo).'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='Coarse stock status: have | low | none.'),
    sa.Column('quantity', sa.Float(), nullable=True, comment='Optional amount; unused by matching/groceries.'),
    sa.Column('unit', sa.String(length=40), nullable=True, comment='Optional unit; unused by matching/groceries.'),
    sa.Column('best_before', sa.Date(), nullable=True, comment='Optional best-before date; display-only.'),
    sa.Column('category', sa.String(length=30), nullable=True, comment='Food category, e.g. protein / vegetable.'),
    sa.Column('opened', sa.Boolean(), nullable=False, comment='Whether the item is opened (carried, unused).'),
    sa.Column('location', sa.String(length=20), nullable=False, comment='Storage location: fridge | shelf | freezer.'),
    sa.PrimaryKeyConstraint('id'),
    comment="Household catalog of stocked foods; matching keys off the unique name, not amounts. Seeded (all 'none') on initial deployment; a future UI edits it."
    )
    op.create_index(op.f('ix_inventory_items_name'), 'inventory_items', ['name'], unique=True)
    op.alter_column('dinner_history', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment='Served recipe (PK part + FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('dinner_history', 'served_on',
               existing_type=sa.DATE(),
               comment='Date served (PK part; household timezone).',
               existing_nullable=False)
    op.alter_column('dinner_history', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='Recipe title snapshot at serve time.',
               existing_nullable=False)
    op.create_table_comment(
        'dinner_history',
        'What was served and when; drives variety exclusion + the history view. (recipe_id, served_on) is the primary key, so re-recording a dinner the same day is an idempotent upsert, not a duplicate.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('ingredients', 'id',
               existing_type=sa.INTEGER(),
               comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ingredients', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('ingredients', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment='Ingredient name.',
               existing_nullable=False)
    op.alter_column('ingredients', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Amount to use.',
               existing_nullable=False)
    op.alter_column('ingredients', 'unit',
               existing_type=sa.VARCHAR(length=40),
               comment='Unit for the amount, e.g. g / each / cup.',
               existing_nullable=False)
    op.alter_column('ingredients', 'position',
               existing_type=sa.INTEGER(),
               comment='Display order within the recipe.',
               existing_nullable=False)
    op.create_table_comment(
        'ingredients',
        'Recipe ingredients with quantity + unit, ordered by position.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('menu_items', 'id',
               existing_type=sa.INTEGER(),
               comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('menu_items', 'menu_id',
               existing_type=sa.INTEGER(),
               comment='Owning menu (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('menu_items', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment='Referenced recipe (FK).',
               existing_nullable=False)
    op.alter_column('menu_items', 'servings',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Number of servings.',
               existing_nullable=False)
    op.create_table_comment(
        'menu_items',
        'Recipes placed on a menu, with servings.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('menus', 'id',
               existing_type=sa.INTEGER(),
               comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('menus', 'for_date',
               existing_type=sa.DATE(),
               comment='Date the menu is for (household timezone).',
               existing_nullable=False)
    op.alter_column('menus', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the menu was generated (UTC).',
               existing_nullable=False)
    op.alter_column('menus', 'notes',
               existing_type=sa.TEXT(),
               comment='Optional free-text notes.',
               existing_nullable=True)
    op.create_table_comment(
        'menus',
        'Generated menus (tonight + planned).',
        existing_comment=None,
        schema=None
    )
    op.alter_column('recipe_equipment', 'id',
               existing_type=sa.INTEGER(),
               comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('recipe_equipment', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_equipment', 'position',
               existing_type=sa.INTEGER(),
               comment='Display order.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('recipe_equipment', 'text',
               existing_type=sa.TEXT(),
               comment='Equipment item.',
               existing_nullable=False)
    op.create_table_comment(
        'recipe_equipment',
        'Equipment needed for the recipe, ordered by position.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('recipe_food_groups', 'id',
               existing_type=sa.INTEGER(),
               comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('recipe_food_groups', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_food_groups', 'food_group',
               existing_type=sa.VARCHAR(length=30),
               comment='Food group: vegetables|fruit|grains|dairy|protein.',
               existing_nullable=False)
    op.alter_column('recipe_food_groups', 'servings',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Servings of that food group.',
               existing_nullable=False)
    op.create_table_comment(
        'recipe_food_groups',
        'Food-group servings a recipe contributes (soft nutrition targets).',
        existing_comment=None,
        schema=None
    )
    op.alter_column('recipe_hazards', 'id',
               existing_type=sa.INTEGER(),
               comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('recipe_hazards', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_hazards', 'flag',
               existing_type=sa.VARCHAR(length=60),
               comment='Hazard flag label.',
               existing_nullable=False)
    op.create_table_comment(
        'recipe_hazards',
        'Safety hazard flags on a recipe (e.g. choking risk).',
        existing_comment=None,
        schema=None
    )
    op.alter_column('recipe_nutrition', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment='Owning recipe (PK + FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_nutrition', 'energy_kcal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Energy (kcal) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'protein_g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Protein (g) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'fat_g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Fat (g) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'carbs_g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Carbohydrate (g) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'fibre_g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Fibre (g) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'iron_mg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Iron (mg) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'calcium_mg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Calcium (mg) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'sodium_mg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Sodium (mg) per serving.',
               existing_nullable=True)
    op.create_table_comment(
        'recipe_nutrition',
        'Per-serving nutrition for a recipe (1:1 with recipes).',
        existing_comment=None,
        schema=None
    )
    op.alter_column('recipe_steps', 'id',
               existing_type=sa.INTEGER(),
               comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('recipe_steps', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_steps', 'position',
               existing_type=sa.INTEGER(),
               comment='Step order.',
               existing_nullable=False)
    op.alter_column('recipe_steps', 'text',
               existing_type=sa.TEXT(),
               comment='Step instruction text.',
               existing_nullable=False)
    op.create_table_comment(
        'recipe_steps',
        'Method steps (one action per row), ordered by position.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('recipe_stickers', 'id',
               existing_type=sa.INTEGER(),
               comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('recipe_stickers', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_stickers', 'content',
               existing_type=sa.TEXT(),
               comment='Handwritten note (<=280 chars).',
               existing_nullable=False)
    op.alter_column('recipe_stickers', 'target_section',
               existing_type=sa.VARCHAR(length=30),
               comment='Pinned section: ingredients|equipment|method|tips, else general (optional).',
               existing_nullable=True)
    op.alter_column('recipe_stickers', 'target_step_id',
               existing_type=sa.INTEGER(),
               comment='Pinned Method step (FK; SET NULL on delete demotes the note to general).',
               existing_nullable=True)
    op.alter_column('recipe_stickers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row creation timestamp (UTC).',
               existing_nullable=False)
    op.alter_column('recipe_stickers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last update timestamp (UTC).',
               existing_nullable=False)
    op.create_table_comment(
        'recipe_stickers',
        'Post-cook handwritten notes pinned to a recipe / section / Method step.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('recipe_tags', 'id',
               existing_type=sa.INTEGER(),
               comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('recipe_tags', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_tags', 'tag',
               existing_type=sa.VARCHAR(length=60),
               comment='Tag label.',
               existing_nullable=False)
    op.create_table_comment(
        'recipe_tags',
        'Free-form tags on a recipe.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('recipe_tips', 'id',
               existing_type=sa.INTEGER(),
               comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('recipe_tips', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_tips', 'position',
               existing_type=sa.INTEGER(),
               comment='Display order.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('recipe_tips', 'text',
               existing_type=sa.TEXT(),
               comment='Tip text.',
               existing_nullable=False)
    op.create_table_comment(
        'recipe_tips',
        'Cooking tips for the recipe, ordered by position.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('recipes', 'id',
               existing_type=sa.INTEGER(),
               comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('recipes', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='Dish name; deduped case-insensitively.',
               existing_nullable=False)
    op.alter_column('recipes', 'min_age_months',
               existing_type=sa.INTEGER(),
               comment='Minimum toddler age (months) the recipe suits.',
               existing_nullable=False)
    op.alter_column('recipes', 'texture',
               existing_type=sa.VARCHAR(length=120),
               comment="Texture note, e.g. 'soft mash' (optional).",
               existing_nullable=True)
    op.alter_column('recipes', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='Origin of the recipe: seed | llm | manual.',
               existing_nullable=False)
    op.alter_column('recipes', 'approved',
               existing_type=sa.BOOLEAN(),
               comment='In the cookbook / auto-suggestable.',
               existing_nullable=False)
    op.alter_column('recipes', 'cooked',
               existing_type=sa.BOOLEAN(),
               comment='Has been eaten (drives history); not auto-suggested on its own.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('recipes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row creation timestamp (UTC).',
               existing_nullable=False)
    op.create_table_comment(
        'recipes',
        'Validated toddler dinner recipes; the cookbook + generation store.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('shopping_items', 'id',
               existing_type=sa.INTEGER(),
               comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('shopping_items', 'shopping_list_id',
               existing_type=sa.INTEGER(),
               comment='Owning shopping list (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('shopping_items', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment='Item name.',
               existing_nullable=False)
    op.alter_column('shopping_items', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Quantity to buy.',
               existing_nullable=False)
    op.alter_column('shopping_items', 'unit',
               existing_type=sa.VARCHAR(length=40),
               comment='Unit for the quantity.',
               existing_nullable=False)
    op.alter_column('shopping_items', 'est_unit_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Estimated unit cost (future; unused in v1).',
               existing_nullable=True)
    op.alter_column('shopping_items', 'est_total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Estimated total cost (future; unused in v1).',
               existing_nullable=True)
    op.alter_column('shopping_items', 'store',
               existing_type=sa.VARCHAR(length=60),
               comment='Store name (future; unused in v1).',
               existing_nullable=True)
    op.alter_column('shopping_items', 'on_special',
               existing_type=sa.BOOLEAN(),
               comment="Whether it's on special (future; unused in v1).",
               existing_nullable=False)
    op.create_table_comment(
        'shopping_items',
        'Items on a shopping list. Cost/store/on_special reserved for future supermarket integration.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('shopping_lists', 'id',
               existing_type=sa.INTEGER(),
               comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('shopping_lists', 'menu_id',
               existing_type=sa.INTEGER(),
               comment='Source menu (FK; SET NULL on delete; optional).',
               existing_nullable=True)
    op.alter_column('shopping_lists', 'budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Budget cap (future; unused in v1).',
               existing_nullable=True)
    op.alter_column('shopping_lists', 'estimated_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Estimated total cost (future; unused in v1).',
               existing_nullable=True)
    op.alter_column('shopping_lists', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the list was generated (UTC).',
               existing_nullable=False)
    op.create_table_comment(
        'shopping_lists',
        'Groceries lists linked to a menu. budget/estimated_total reserved for future supermarket integration.',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'shopping_lists',
        existing_comment='Groceries lists linked to a menu. budget/estimated_total reserved for future supermarket integration.',
        schema=None
    )
    op.alter_column('shopping_lists', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the list was generated (UTC).',
               existing_nullable=False)
    op.alter_column('shopping_lists', 'estimated_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Estimated total cost (future; unused in v1).',
               existing_nullable=True)
    op.alter_column('shopping_lists', 'budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Budget cap (future; unused in v1).',
               existing_nullable=True)
    op.alter_column('shopping_lists', 'menu_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Source menu (FK; SET NULL on delete; optional).',
               existing_nullable=True)
    op.alter_column('shopping_lists', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'shopping_items',
        existing_comment='Items on a shopping list. Cost/store/on_special reserved for future supermarket integration.',
        schema=None
    )
    op.alter_column('shopping_items', 'on_special',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="Whether it's on special (future; unused in v1).",
               existing_nullable=False)
    op.alter_column('shopping_items', 'store',
               existing_type=sa.VARCHAR(length=60),
               comment=None,
               existing_comment='Store name (future; unused in v1).',
               existing_nullable=True)
    op.alter_column('shopping_items', 'est_total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Estimated total cost (future; unused in v1).',
               existing_nullable=True)
    op.alter_column('shopping_items', 'est_unit_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Estimated unit cost (future; unused in v1).',
               existing_nullable=True)
    op.alter_column('shopping_items', 'unit',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment='Unit for the quantity.',
               existing_nullable=False)
    op.alter_column('shopping_items', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Quantity to buy.',
               existing_nullable=False)
    op.alter_column('shopping_items', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment=None,
               existing_comment='Item name.',
               existing_nullable=False)
    op.alter_column('shopping_items', 'shopping_list_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Owning shopping list (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('shopping_items', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'recipes',
        existing_comment='Validated toddler dinner recipes; the cookbook + generation store.',
        schema=None
    )
    op.alter_column('recipes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row creation timestamp (UTC).',
               existing_nullable=False)
    op.alter_column('recipes', 'cooked',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Has been eaten (drives history); not auto-suggested on its own.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('recipes', 'approved',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='In the cookbook / auto-suggestable.',
               existing_nullable=False)
    op.alter_column('recipes', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Origin of the recipe: seed | llm | manual.',
               existing_nullable=False)
    op.alter_column('recipes', 'texture',
               existing_type=sa.VARCHAR(length=120),
               comment=None,
               existing_comment="Texture note, e.g. 'soft mash' (optional).",
               existing_nullable=True)
    op.alter_column('recipes', 'min_age_months',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Minimum toddler age (months) the recipe suits.',
               existing_nullable=False)
    op.alter_column('recipes', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Dish name; deduped case-insensitively.',
               existing_nullable=False)
    op.alter_column('recipes', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'recipe_tips',
        existing_comment='Cooking tips for the recipe, ordered by position.',
        schema=None
    )
    op.alter_column('recipe_tips', 'text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Tip text.',
               existing_nullable=False)
    op.alter_column('recipe_tips', 'position',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Display order.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('recipe_tips', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_tips', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'recipe_tags',
        existing_comment='Free-form tags on a recipe.',
        schema=None
    )
    op.alter_column('recipe_tags', 'tag',
               existing_type=sa.VARCHAR(length=60),
               comment=None,
               existing_comment='Tag label.',
               existing_nullable=False)
    op.alter_column('recipe_tags', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_tags', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'recipe_stickers',
        existing_comment='Post-cook handwritten notes pinned to a recipe / section / Method step.',
        schema=None
    )
    op.alter_column('recipe_stickers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last update timestamp (UTC).',
               existing_nullable=False)
    op.alter_column('recipe_stickers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row creation timestamp (UTC).',
               existing_nullable=False)
    op.alter_column('recipe_stickers', 'target_step_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Pinned Method step (FK; SET NULL on delete demotes the note to general).',
               existing_nullable=True)
    op.alter_column('recipe_stickers', 'target_section',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Pinned section: ingredients|equipment|method|tips, else general (optional).',
               existing_nullable=True)
    op.alter_column('recipe_stickers', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Handwritten note (<=280 chars).',
               existing_nullable=False)
    op.alter_column('recipe_stickers', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_stickers', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'recipe_steps',
        existing_comment='Method steps (one action per row), ordered by position.',
        schema=None
    )
    op.alter_column('recipe_steps', 'text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Step instruction text.',
               existing_nullable=False)
    op.alter_column('recipe_steps', 'position',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Step order.',
               existing_nullable=False)
    op.alter_column('recipe_steps', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_steps', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'recipe_nutrition',
        existing_comment='Per-serving nutrition for a recipe (1:1 with recipes).',
        schema=None
    )
    op.alter_column('recipe_nutrition', 'sodium_mg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Sodium (mg) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'calcium_mg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Calcium (mg) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'iron_mg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Iron (mg) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'fibre_g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Fibre (g) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'carbs_g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Carbohydrate (g) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'fat_g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Fat (g) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'protein_g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Protein (g) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'energy_kcal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Energy (kcal) per serving.',
               existing_nullable=True)
    op.alter_column('recipe_nutrition', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Owning recipe (PK + FK, cascade delete).',
               existing_nullable=False)
    op.drop_table_comment(
        'recipe_hazards',
        existing_comment='Safety hazard flags on a recipe (e.g. choking risk).',
        schema=None
    )
    op.alter_column('recipe_hazards', 'flag',
               existing_type=sa.VARCHAR(length=60),
               comment=None,
               existing_comment='Hazard flag label.',
               existing_nullable=False)
    op.alter_column('recipe_hazards', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_hazards', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'recipe_food_groups',
        existing_comment='Food-group servings a recipe contributes (soft nutrition targets).',
        schema=None
    )
    op.alter_column('recipe_food_groups', 'servings',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Servings of that food group.',
               existing_nullable=False)
    op.alter_column('recipe_food_groups', 'food_group',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Food group: vegetables|fruit|grains|dairy|protein.',
               existing_nullable=False)
    op.alter_column('recipe_food_groups', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_food_groups', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'recipe_equipment',
        existing_comment='Equipment needed for the recipe, ordered by position.',
        schema=None
    )
    op.alter_column('recipe_equipment', 'text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Equipment item.',
               existing_nullable=False)
    op.alter_column('recipe_equipment', 'position',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Display order.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('recipe_equipment', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('recipe_equipment', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'menus',
        existing_comment='Generated menus (tonight + planned).',
        schema=None
    )
    op.alter_column('menus', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Optional free-text notes.',
               existing_nullable=True)
    op.alter_column('menus', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the menu was generated (UTC).',
               existing_nullable=False)
    op.alter_column('menus', 'for_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date the menu is for (household timezone).',
               existing_nullable=False)
    op.alter_column('menus', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'menu_items',
        existing_comment='Recipes placed on a menu, with servings.',
        schema=None
    )
    op.alter_column('menu_items', 'servings',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Number of servings.',
               existing_nullable=False)
    op.alter_column('menu_items', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Referenced recipe (FK).',
               existing_nullable=False)
    op.alter_column('menu_items', 'menu_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Owning menu (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('menu_items', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'ingredients',
        existing_comment='Recipe ingredients with quantity + unit, ordered by position.',
        schema=None
    )
    op.alter_column('ingredients', 'position',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Display order within the recipe.',
               existing_nullable=False)
    op.alter_column('ingredients', 'unit',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment='Unit for the amount, e.g. g / each / cup.',
               existing_nullable=False)
    op.alter_column('ingredients', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Amount to use.',
               existing_nullable=False)
    op.alter_column('ingredients', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment=None,
               existing_comment='Ingredient name.',
               existing_nullable=False)
    op.alter_column('ingredients', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Owning recipe (FK, cascade delete).',
               existing_nullable=False)
    op.alter_column('ingredients', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Surrogate primary key.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'dinner_history',
        existing_comment='What was served and when; drives variety exclusion + the history view. (recipe_id, served_on) is the primary key, so re-recording a dinner the same day is an idempotent upsert, not a duplicate.',
        schema=None
    )
    op.alter_column('dinner_history', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Recipe title snapshot at serve time.',
               existing_nullable=False)
    op.alter_column('dinner_history', 'served_on',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date served (PK part; household timezone).',
               existing_nullable=False)
    op.alter_column('dinner_history', 'recipe_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Served recipe (PK part + FK, cascade delete).',
               existing_nullable=False)
    op.drop_index(op.f('ix_inventory_items_name'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
